# Site settings
title: Michael Ashton
email: ashton@mpie.de
url: michael-ashton.com
baseurl: ""
description: "Science + Software + Some other stuff"
phone: +49 176 329 81187
address: Corintostrasse 2</br>Cologne, Germany 51103
keywords: "Science, Software, Materials, Programmer, Coding, Development, Resume, CV, Physics, Research"
meta_author: Ashton Michael

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: formbutton

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

style:
  padding-transition: 600px
  flex-transition: 500px

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: rgba(255, 59, 45, 1) #ff3b2d
  secondary: rgba(255, 95, 67) #ff4c1f

  particles: rgba(255,255,255,0.5)
  particle-lines: rgba(255,255,255,0.5)

# Footer settings
footer:
  copyright: Michael Ashton

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google
    url: http://scholar.google.com/citations?user=SgAQKZIAAAAJ&hl=en
  - title: github
    url: http://github.com/ashtonmv
  - title: linkedin
    url: http://www.linkedin.com/in/michael-ashton/
  - title: researchgate
    url: https://www.researchgate.net/profile/Michael_Ashton6

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
