# Site settings
title: Particular
email: particular@gmail.com
url: michael-ashton.com
baseurl:
description: A clean, comfortable home for your resumé.
phone: +0 867 5309
address: Street 1</br>City, Country ZIPCODE  # Don't forget the <br>
keywords: Science, Software, Programmer, Coding, Development, Resume, CV, Physics, Research
meta_author: Ashton Michael

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
